spring.application.name=Ex19AssoMapping

# thymeleaf
spring.thymeleaf.cache=false

# H2 Database
# mem : \uBA54\uBAA8\uB9AC DB\uC774\uBBC0\uB85C \uC571 \uC2E4\uD589\uC2DC\uC5D0\uB9CC \uC720\uB8CC\uD568. \uC885\uB8CC\uD558\uBA74 \uC0AC\uB77C\uC9D0.
# testdb : \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC774\uB984
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
# H2 \uC544\uC774\uB514/\uC554\uD638
spring.datasource.username=sa
spring.datasource.password=

# JPA
# none : \uC544\uBB34\uC77C\uB3C4 \uD558\uC9C0 \uC54A\uB294\uB2E4.
# validate : \uC2E4DB\uB791 \uBE44\uAD50\uD574\uC11C \uB2E4\uB974\uBA74, \uC624\uB958\uBC1C\uC0DD
# create : \uAE30\uC874\uD14C\uC774\uBE14 \uC9C0\uC6B0\uACE0, \uC5D4\uD2F0\uD2F0 \uD074\uB798\uC2A4\uC758 \uB0B4\uC6A9\uC744 \uD14C\uC774\uBE14 \uC0DD\uC131
# create-drop : \uC571\uC885\uB8CC\uC2DC \uC2E4DB \uD14C\uC774\uBE14 \uC9C0\uC6B4\uB2E4.
# update : \uC2E4DB\uC640 \uC5D4\uD2F0\uD2F0 \uB0B4\uC6A9\uC774 \uB2E4\uB974\uBA74 \uC5C5\uB370\uC774\uD2B8\uD55C\uB2E4.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 Console
# \uC571\uC2E4\uD589 \uC911 localhost:8080/h2console \uC811\uC18D
spring.h2.console.enabled=true
