# thymeleaf
spring.thymeleaf.cache=false

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# sql pretty
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# DATABASE - MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# logging
logging.level.org.hibernate.type.description.sql.BasicBinder=trace
logging.level.org.hibernate.SQL=debug
# Hibernate 6.1.5 updated in springboot 3.x, 4.x
logging.level.org.hibernate.orm.jdbc.bind=trace

# profiles
spring.profiles.include=secret

# JWT token
jwt.secretKey=${JWT_SECRET_KEY}
# 1day ( 1000 * 60 * 60 * 24 )
jwt.expiration_time=86400000
